"""add ai complaint fields

Revision ID: 53617d6c796c
Revises: d40af2ceeac4
Create Date: 2026-06-10 15:52:00.740436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53617d6c796c'
down_revision: Union[str, Sequence[str], None] = 'd40af2ceeac4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('ai_category', sa.String(length=100), nullable=False, server_default='Unknown'))
    op.add_column('complaints', sa.Column('priority', sa.String(length=50), nullable=False, server_default='Medium'))
    op.add_column('complaints', sa.Column('severity_score', sa.Integer(), nullable=False, server_default='5'))
    op.add_column('complaints', sa.Column('recommended_department', sa.String(length=255), nullable=False, server_default='General Administration'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'recommended_department')
    op.drop_column('complaints', 'severity_score')
    op.drop_column('complaints', 'priority')
    op.drop_column('complaints', 'ai_category')
    # ### end Alembic commands ###
