"""add ward to complaints

Revision ID: cf896d5fcc35
Revises: 53617d6c796c
Create Date: 2026-06-11 12:44:42.722139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf896d5fcc35'
down_revision: Union[str, Sequence[str], None] = '53617d6c796c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_scores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ward_name', sa.String(length=100), nullable=False),
    sa.Column('complaint_count', sa.Integer(), nullable=False),
    sa.Column('average_severity', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('recommendation', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column( 'complaints',   sa.Column(  'ward_name', sa.String(length=100),nullable=False,server_default='Ward 1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'ward_name')
    op.drop_table('risk_scores')
    # ### end Alembic commands ###
